---
micronaut:
  application:
    name: consumer-sample
  executors:
    consumer:
      type: fixed
      nThreads: 25
datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
jpa:
  default:
    packages-to-scan:
      - 'com.mnkafka.sample.consumer.jpa'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
application:
  max: 50
---
kafka:
    bootstrap:
        servers: localhost:9092